"""drop extra_data column from Alert

Revision ID: e1932c411f61
Revises: 2b4dd4b88121
Create Date: 2026-05-12 15:17:56.475778

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1932c411f61"
down_revision = "2b4dd4b88121"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_column("extra_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "extra_data",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
    # ### end Alembic commands ###
